name: Java CI
on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: 'oracle'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run Style Check
        run: ./mvnw checkstyle:check

      # This runs your tests. If you have no tests, it just compiles.
      - name: Build with Maven
        run: ./mvnw clean verify
